### ISSUE TITLE
Incorta is a Data Analytics and BI platform

### ISSUE THREAD

**Issue by MohamedElPrince** [harryadel/AI-ML-Driven-Companies-In-Egypt#5]
Incorta is an end-to-end Data Analytics and BI platform not related to robotics and computer vision

**Comment by harryadel** [comment]
Thanks, fixed in https://github.com/harryadel/AI-ML-Driven-Companies-In-Egypt/commit/fe59f7afe9ed4552b556dd681c88a5679f86821e

**Comment by Abdallah-nassa** [comment]
Okay Sent from Mail for Windows From: Harry AdelSent: Tuesday, May 30, 2023 11:49 AMTo: harryadel/AI-ML-Driven-Companies-In-EgyptCc: SubscribedSubject: Re: [harryadel/AI-ML-Driven-Companies-In-Egypt] Incorta is a Data Analytics and BI platform (Issue #5) Thanks, fixed in fe59f7a—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
